# Generated by Django 5.0.3 on 2024-03-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LocationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=255, verbose_name="город")),
                ("state", models.CharField(max_length=255, verbose_name="штат")),
                (
                    "zip",
                    models.CharField(max_length=255, verbose_name="почтовый индекс"),
                ),
                ("latitude", models.CharField(max_length=255, verbose_name="широта")),
                ("longitude", models.CharField(max_length=255, verbose_name="долгота")),
            ],
            options={
                "verbose_name": "локация",
                "verbose_name_plural": "локации",
            },
        ),
    ]
