# Generated by Django 5.0.3 on 2024-03-27 17:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("location", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        editable=False,
                        max_length=5,
                        unique=True,
                        verbose_name="уникальный номер",
                    ),
                ),
                (
                    "load_capacity",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                        verbose_name="грузоподъемность",
                    ),
                ),
                (
                    "current_location",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="location.locationmodel",
                        verbose_name="текущая локация",
                    ),
                ),
            ],
        ),
    ]
