# Generated by Django 5.0.3 on 2024-03-27 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="carsmodel",
            options={"verbose_name": "машина", "verbose_name_plural": "машины"},
        ),
    ]
