# Generated by Django 5.0.3 on 2024-03-27 17:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("location", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CargoModels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                        verbose_name="вес",
                    ),
                ),
                ("description", models.TextField(verbose_name="описание")),
                (
                    "delivery_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_location",
                        to="location.locationmodel",
                        verbose_name="локация delivery",
                    ),
                ),
                (
                    "pick_up_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pick_up_location",
                        to="location.locationmodel",
                        verbose_name="локация pick-up",
                    ),
                ),
            ],
            options={
                "verbose_name": "груз",
                "verbose_name_plural": "груз",
            },
        ),
    ]
